# Generated by Django 2.2.8 on 2022-03-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_devicelogin_device_temporal_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicelogin',
            name='device_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
